In [35]:
# Import Statements
import torch

In [36]:
# The AutoGrad Package (autograd) is a key package for neural networks in PyTorch.
# Tensor and Function

tensor_one = torch.ones(2, 2, requires_grad=True)
print(tensor_one)
print(tensor_one.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [37]:
tensor_two = tensor_one + 2
print(tensor_two)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [38]:
print(tensor_two.grad_fn)

In [39]:
tensor_three = tensor_two * tensor_two * 3
out = tensor_three.mean()
print(out, tensor_three)

tensor(27., grad_fn=<MeanBackward1>) tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)


In [40]:
tensor_four = torch.randn(2, 2)
tensor_four = ((tensor_four * 3) / (tensor_four - 1))
print(tensor_four.grad_fn)
print(tensor_four.requires_grad)
tensor_four.requires_grad_(True)
print(tensor_four.requires_grad)

tensor_five = (tensor_four * tensor_four).sum()
print(tensor_five.grad_fn)

None
False
True


In [41]:
# Gradients
out.backward()
print(tensor_one.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [42]:
# Generally speaking, torch.autograd is an engine for computing vector-Jacobian product.
tensor_six = torch.randn(3, requires_grad=True)

tensor_seven = tensor_six * 2

while tensor_seven.data.norm() < 1000:
    tensor_seven = tensor_seven * 2
print(tensor_seven)

tensor([-1165.0070,  -518.5812,  -310.6064], grad_fn=<MulBackward0>)


In [43]:
tensor_eight = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
tensor_seven.backward(tensor_eight)
print(tensor_six.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [44]:
print(tensor_six.requires_grad)
print((tensor_six ** 2).requires_grad)

with torch.no_grad():
    print((tensor_six ** 2).requires_grad)

True
True
False


In [45]:
print(tensor_six.requires_grad)
tensor_nine = tensor_six.detach()
print(tensor_nine.requires_grad)
print(tensor_six.eq(tensor_nine).all())

True
False
tensor(1, dtype=torch.uint8)
